### ISSUE TITLE
Upload model

### ISSUE THREAD

**Issue by birbilis** [NetLogo/Tortoise#150]
at
https://github.com/NetLogo/NetLogo/wiki/Tortoise
says Try it out! and points to
http://li425-91.members.linode.com:9000/create-standalone

where the 2nd Submit button (where you peek existing model first) seems to work, but not the 1st one (where you upload a model file)

**Comment by TheBizzle** [comment]
I'm not sure I understand the issue.  Is the problem that you're not able to upload a model file?  Did you try clicking the input box that says "Select a file..."?  If so, what is going wrong?

**Comment by birbilis** [comment]
I select file, then after it tries to upload I get back HTTP 500 (internal server error)

**Comment by TheBizzle** [comment]
I see some errors about a model having fewer sections than necessary, but I don't know which of these logged errors is yours.  Could you send us a copy of the model you're uploading that causes this problem?

**Comment by birbilis** [comment]
I can send it via e-mail as long as it is kept private (since it's still work in progress)

**Comment by birbilis** [comment]
btw, I've already tried 2-3 times, so if you see the same error, it's from my file that works fine in NetLogo

**Comment by TheBizzle** [comment]
Yeah, we'll have to support storing user models one day, I think, but I think that's not a high enough priority at the moment.  One day.

Please forward the `.nlogo` file to me at jason.bertsche@northwestern.edu .

**Comment by birbilis** [comment]
ok, sent it, let me know if you need any info on how to use it

**Comment by TheBizzle** [comment]
Your model is failing with the message 

> Nothing named __CLEAR-ALL-AND-RESET-TICKS has been defined.

Your code uses the `__clear-all-and-reset-ticks` primitive, which only exists in JVM NetLogo for backwards compatibility with older versions of NetLogo.  That primitive is not supported in NetLogo Web and will never be.  The workaround for that particular issue is very easy, though: replace `__clear-all-and-reset-ticks` with `clear-all reset-ticks`.

You'll still run into problems with this model, though.  For one, it uses the Profiler extension.  Extensions aren't supported at all right now in NetLogo Web, and it will be a while before they are.  It is unknown whether or not a Profiler extension will ever be implemented for NetLogo Web, even once extensions are supported.

If you comment out the stuff with the Profiler extension, this model *still* has problems, unfortunately.  It uses many currently-unimplemented primitives:
  * `sort-by`
    * Not straightforward to work around in NetLogo code
  * `beep`
    * A personal favorite primitive of mine, but not likely to be supported anytime soon
  * `run` (on a string)
    * We support `run` on tasks, but not on strings ([ticket](https://github.com/NetLogo/Tortoise/issues/122)).  I don't think we've made a strong decision yet about whether or not `run`/`runresult` will ever support strings.  It'd be nice if everything could be done with tasks, but your models has one of those more-compelling arguments for being able to use it on strings.
  * `display`
    * This primitive won't prevent your model from compiling, but calling it in NetLogo Web does nothing.  Getting this working involves tackling a pretty tricky JavaScript issue ([ticket](https://github.com/NetLogo/Tortoise/issues/13)).

But, wait, there's more!  Even if you work around all of the problems listed above, there's still a grievous issue with the model.  `edit-make-connectors` is an essential part of this model.  You basically can't do anything without it.  But that procedure calls `wait-mouse-up` when the mouse is down, which contains the code `while [mouse-down?] []`.  This compiles to `while (MousePrims.isDown()) {}` in JavaScript, which is actually a massive problem, because JavaScript will never let this value change while the `while` loop is running.  Our standard mouse-dragging model (Mouse Drag One Example) has a similar issue.

At this point, I think I just have to say that NetLogo Web is not yet in a good enough state to run your model.  There's clearly lots of room for improvement on our end, and this model actually demonstrates a lot of problems that need to be addressed by us.

Anyway, thanks for the report.  I'm going to close this issue and make a separate one for mouse-dragging issue.

**Comment by SethTisue** [comment]
note that it's preferable to move `reset-ticks` to the end of `setup`, for view updates and plotting to happen at the right time; see http://ccl.northwestern.edu/netlogo/docs/programming.html#ticks,

**Comment by birbilis** [comment]
indeed, hadn't noticed NetLogo had injected this note at "reset"

  ;; (for this model to work with NetLogo's new plotting features,
  ;; __clear-all-and-reset-ticks should be replaced with clear-all at
  ;; the beginning of your setup procedure and reset-ticks at the end
  ;; of the procedure.)
