### ISSUE TITLE
Pages can crash from high memory usage

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#168]
In Chrome this just kills the tab. in FireFox it takes a couple gigabytes to load and keeps growing even without pressing setup or go.

NLOGO: https://drive.google.com/file/d/0B0taMM6vlEqQLUx0MV92bVNYOXM/view?usp=sharing

HTML: https://drive.google.com/file/d/0B0taMM6vlEqQUzI5OXoyMmFpeGM/view?usp=sharing

The world is 801x801 -- changing it to 401x401 fixes the problem.

**Comment by TheBizzle** [comment]
Yeah, whether or not it crashes seems to vary across browsers.  I'm not sure what we can realistically do about this, though.

**Comment by mrerrormessage** [comment]
This seems like a very similar issue to https://github.com/NetLogo/NetLogo/issues/587, with the key difference that the JVM (and the tried-and-true NetLogo implementation) can hold many, many more patches than current JS runtimes.

**Comment by ToonTalk** [comment]
801x801 is about 640K patches -- why would this require more than two gigabytes of storage?

**Comment by LaCuneta** [comment]
I updated the linked Acoustics model to NetLogo 6.1.1 and ran it with the latest Tortoise engine and it worked in Firefox, Safari, and Chrome without a crash.  The model ran slowly, but no out of memory issues.  

We've had a few memory-saving optimizations done since this issue was made, most recently [this one which was meant to help models with large-size worlds (like Acoustics)](https://github.com/NetLogo/Tortoise/commit/ad59c04681364402ce137bb1ceb1ff12d033ad76) and [this one for models with lots of dying, breeded agents](https://github.com/NetLogo/Tortoise/commit/f3a6167a9a5c2cb34b7956de7b55ddd9b3c5526a).

It seems like this is resolved for now, and we'll keep working on performance improvements to make models with lots of agents and large worlds run at speeds closer to desktop.
